### ISSUE TITLE
在AS3.6 上启动崩了

### ISSUE THREAD

**Issue by woxingxiao** [misakuo/svgtoandroid#48]
这个工具非常棒，请大佬尽快修复（抱拳了
```java
java.lang.NullPointerException
	at com.moxun.s2v.utils.CommonUtil.loadMetaInf(CommonUtil.java:56)
	at com.moxun.s2v.GUI.<init>(GUI.java:48)
	at com.moxun.s2v.S2V.actionPerformed(S2V.java:14)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:265)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:256)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:194)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:157)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:434)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:823)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by BuWeijing** [comment]
我的是3.6.1，也是这个情况

**Comment by BuWeijing** [comment]
> 这个工具非常棒，请大佬尽快修复（抱拳了
> 
> ```java
> java.lang.NullPointerException
> 	at com.moxun.s2v.utils.CommonUtil.loadMetaInf(CommonUtil.java:56)
> 	at com.moxun.s2v.GUI.<init>(GUI.java:48)
> 	at com.moxun.s2v.S2V.actionPerformed(S2V.java:14)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:265)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
> 	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:256)
> 	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:194)
> 	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:157)
> 	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:434)
> 	at java.awt.Component.processEvent(Component.java:6315)
> 	at java.awt.Container.processEvent(Container.java:2239)
> 	at java.awt.Component.dispatchEventImpl(Component.java:4899)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2297)
> 	at java.awt.Component.dispatchEvent(Component.java:4721)
> 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
> 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
> 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
> 	at java.awt.Container.dispatchEventImpl(Container.java:2283)
> 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
> 	at java.awt.Component.dispatchEvent(Component.java:4721)
> 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
> 	at java.awt.EventQueue.access$500(EventQueue.java:98)
> 	at java.awt.EventQueue$3.run(EventQueue.java:715)
> 	at java.awt.EventQueue$3.run(EventQueue.java:709)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
> 	at java.awt.EventQueue$4.run(EventQueue.java:739)
> 	at java.awt.EventQueue$4.run(EventQueue.java:737)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
> 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:878)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:823)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:466)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:465)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> ```

new -> vector asset 可以把svg直接生成xml

**Comment by cl136787252** [comment]
我也是升级Android studio 3.6.1，这个插件就打不开报这个错误，希望大佬是马上修复这个问题，现在真的离不开这个插件了

**Comment by misakuo** [comment]
感谢支持！非常高兴这个小工具能给你们带来帮助。工作比较忙，我尽快抽空修复这个问题：）

**Comment by misakuo** [comment]
请更新至1.8.2版本，Thanks
